import graphviz
import streamlit as st
graph = graphviz.Graph()

graph.edge( 'a' , 'b')
graph.edge( 'a' , 'c')
graph.edge( 'c' , 'd')
graph.edge( 'c' , 'j')
graph.edge( 'j' , 'f')
graph.edge( 'j' , 'd')
graph.edge( 'j' , 'e')
graph.edge( 'l' , 'e')
graph.edge( 'k' , 'l')
graph.edge( 'k' , 'j')
graph.edge( 'i' , 'j')
graph.edge( 'i' , 'h')
graph.edge( 'i' , 'g')
graph.edge( 'l' , 'n')
graph.edge( 'l' , 'm')
graph.edge( 'm' , 'o')
graph.edge( 'n' , 'o')
graph.edge( 'w' , 'v')
graph.edge( 'k' , 'x')
graph.edge( 'w' , 'l')
graph.edge( 'v' , 'x')
graph.edge( 'x' , 'y')
graph.edge( 'v' , 't')
graph.edge( 't' , 'u')
graph.edge( 't' , 'o')
graph.edge( 'o' , 'p')
graph.edge('p', 'q')
graph.edge('q', 's')
graph.edge('q', 'r')
st.graphviz_chart(graph,use_container_width=True)